# Generated by Django 3.1.5 on 2021-02-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('p_desc', models.TextField(blank=True, null=True)),
                ('p_price', models.CharField(max_length=10)),
            ],
        ),
    ]
