# Generated by Django 3.1.5 on 2021-02-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_img',
            field=models.ImageField(blank=True, null=True, upload_to='p_img'),
        ),
    ]
