# Generated by Django 3.1.5 on 2021-02-06 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_p_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instant',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
